version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3316:3306'
    expose:
      - 3316
    volumes:
      - db_data:/var/lib/mysql

  dbeaver:
    build:
      context: ./dbeaver
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=host.docker.internal
      - DB_PORT=3316
    ports:
      - 8080:8080
    depends_on:
      - db

  dbeaver-mvc:
    build:
      context: ./dbeaver-mvc
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=host.docker.internal
      - DB_PORT=3316
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db_data: {}